; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\Users\cahiggi\Code\ASM\RE-For-Beginners\alloca.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2890	DB	'hi! %d, %d, %d', 0aH, 00H
_DATA	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	_f
EXTRN	_puts:PROC
EXTRN	__snprintf:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__alloca_probe_16:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv66 = -12						; size = 4
__$ArrayPad$ = -8					; size = 4
_buf$ = -4						; size = 4
_f	PROC
; File c:\users\cahiggi\code\asm\re-for-beginners\alloca.c
; Line 8
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 9
	mov	eax, 600				; 00000258H
	call	__alloca_probe_16
	mov	DWORD PTR tv66[ebp], esp
	mov	eax, DWORD PTR tv66[ebp]
	mov	DWORD PTR _buf$[ebp], eax
; Line 13
	push	3
	push	2
	push	1
	push	OFFSET $SG2890
	push	600					; 00000258H
	mov	ecx, DWORD PTR _buf$[ebp]
	push	ecx
	call	__snprintf
	add	esp, 24					; 00000018H
; Line 15
	mov	edx, DWORD PTR _buf$[ebp]
	push	edx
	call	_puts
	add	esp, 4
; Line 16
	lea	esp, DWORD PTR [ebp-12]
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 18
	push	ebp
	mov	ebp, esp
; Line 19
	call	_f
; Line 20
	xor	eax, eax
; Line 21
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
