; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\Users\cahiggi\Code\ASM\RE-For-Beginners\garbage_vars.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2752	DB	'%d, %d, %d', 0aH, 00H
_DATA	ENDS
PUBLIC	_f1
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f1	PROC
; File c:\users\cahiggi\code\asm\re-for-beginners\garbage_vars.c
; Line 3
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 5
	mov	esp, ebp
	pop	ebp
	ret	0
_f1	ENDP
_TEXT	ENDS
PUBLIC	_f2
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_c$ = -12						; size = 4
_b$ = -8						; size = 4
_a$ = -4						; size = 4
_f2	PROC
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 9
	mov	eax, DWORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _b$[ebp]
	push	ecx
	mov	edx, DWORD PTR _a$[ebp]
	push	edx
	push	OFFSET $SG2752
	call	_printf
	add	esp, 16					; 00000010H
; Line 10
	mov	esp, ebp
	pop	ebp
	ret	0
_f2	ENDP
_TEXT	ENDS
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; Line 12
	push	ebp
	mov	ebp, esp
; Line 13
	call	_f1
; Line 14
	call	_f2
; Line 15
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
