; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\Users\cahiggi\Code\ASM\RE-For-Beginners\printf_2.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2744	DB	'a=%d; b=%d; c=%d; d=%d; e=%d; f=%d; g=%d; h=%d', 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\users\cahiggi\code\asm\re-for-beginners\printf_2.c
; Line 3
	push	ebp
	mov	ebp, esp
; Line 4
	push	8
	push	7
	push	6
	push	5
	push	4
	push	3
	push	2
	push	1
	push	OFFSET $SG2744
	call	DWORD PTR __imp__printf
	add	esp, 36					; 00000024H
; Line 5
	xor	eax, eax
; Line 6
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
