; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\Users\cahiggi\Code\ASM\RE-For-Beginners\scanf.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2745	DB	'Enter X:', 0aH, 00H
	ORG $+2
$SG2746	DB	'%d', 00H
	ORG $+1
$SG2747	DB	'You entered %d...', 0aH, 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	__imp__scanf:PROC
EXTRN	__imp__printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_x$ = -4						; size = 4
_main	PROC
; File c:\users\cahiggi\code\asm\re-for-beginners\scanf.c
; Line 3
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 5
	push	OFFSET $SG2745
	call	DWORD PTR __imp__printf
	add	esp, 4
; Line 6
	lea	eax, DWORD PTR _x$[ebp]
	push	eax
	push	OFFSET $SG2746
	call	DWORD PTR __imp__scanf
	add	esp, 8
; Line 7
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	push	OFFSET $SG2747
	call	DWORD PTR __imp__printf
	add	esp, 8
; Line 8
	xor	eax, eax
; Line 9
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
